### PR TITLE
Added theme switcher

### PR DESCRIPTION
**Pull request by ufrshubham**
I am adding a button right next to date picker to switch between dark and light themes. Theme mode will be stored persistently using hive box. This is how it will look.

ThemeSwitch

### CODE REVIEW

**Comment by sainiteshb** [comment]
hey thats really good!

**Comment by sainiteshb** [comment]
can you change the position to left

**Comment by sainiteshb** [comment]
i will change it

**Comment by ufrshubham** [comment]
Sure. Just to be clear, left of the date widget or to extreme left?

**Comment by ufrshubham** [comment]
Oh, you closed it. 🤘🏻

**Pull request merged**
