### PR TITLE
Added instant caching of api calls

### PR DESCRIPTION
**Pull request by kavienanj**
This caches the API calls with Hive storage. With few more logic, this can be turned into an offline app. But for now, if no connection found it will not lookup for the cache.

### CODE REVIEW

**Comment by sainiteshb** [comment]
Have you tried running on a physical device

**Comment by sainiteshb** [comment]
Awesome job 🔥

**Comment by kavienanj** [comment]
I didnt try it in a physical device.
But if the earier code ran well in a physical device this should run too.

**Comment by sainiteshb** [comment]
Alright, Also you mentioned adding logic  can make it more like an offline app. Are you working on it?

**Comment by kavienanj** [comment]
Sure I can do that too!

**Comment by kavienanj** [comment]
It's better if you can open an issue and assign it to me.

**Comment by sainiteshb** [comment]
Okay i think i cant assign it without  you opening an issue , so maybe open one and I will assign you.

**Comment by kavienanj** [comment]
Done👍. See issue #11

**Pull request merged**
