### PR TITLE
We can swipe now!

### LINKED ISSUE #6: Swipe option to view previous days APOD
Add swiping feature to move to previous or next days APOD.

### PR DESCRIPTION
**Pull request by ufrshubham**
This pull request will close #6 .

I have added two new files:

- _models/apodModel.dart_ : Contains a simple model class to make it easy to pass around data of an APOD.

- _providers/apod_provider.dart_ : Contains **ApodProvider** class extended from ChangeNotifier. This class holds a **DateTime** object and contains **getApodData()** method which fetches APOD data by calling the the APOD API with parameters from stored **DateTime** object. It also provides a method called **changeDate()**, using which we can change the stored **DateTime** object. Every call to **changeDate()** will notify all the listeners to rebuild.

Additionally I have also refactored most of the code into small methods to make it easier to maintain and debug.

@sainiteshb last time I added a .gitignore file so that unnecessary files don't get pushed to this repo, but you seem to have remove it. So I am not added it back again. So expect to see unwanted files like android/local.properties being pushed. 😅

### CODE REVIEW

**Comment by sainiteshb** [comment]
have you tested it in an emulator , if yes can you please share the screenshot or video, just to have an overlook . 😀

**Comment by sainiteshb** [comment]
also add the gitignore file , i am sorry i deleted it by mistake

**Comment by ufrshubham** [comment]
Here is how it will look.
swpie

**Comment by ufrshubham** [comment]
> also add the gitignore file , i am sorry i deleted it by mistake

Added again.

**Comment by sainiteshb** [comment]
Awesome job @ufrshubham  🔥

**Pull request merged**
